### ISSUE TITLE
docker - HomeKitServer - HomekitRoot constructor with JmdnsHomekitAdvertiser never called

### ISSUE THREAD

**Issue by gpr7700** [hap-java/HAP-Java#100]
**Environment**
- raspberry 4
- hypriotOS
- openhab in docker
- AVAHI active reflector enabled (enable-reflector=yes - /etc/avahi/avahi-daemon.conf)

**Issue**
The bridge (_hap._tcp) is never advertised when specifying the **host container ip** address.
With container ip address bridge is advertised.

When looking at the code it seems that HomeKitServer (createBridge) never calls the HomekitRoot constructor that takes the JmdnsHomekitAdvertiser instance. Therefore the bridge is not advertised and you have no logs at all to investigate why something is going wrong.

Regards

Gregory

**Comment by J-N-K** [comment]
Why should it call that constructor? If no advertiser is given, a new one is created and passed to the very same constructor that would be used if you pass an advertiser.

**Comment by gpr7700** [comment]
Hi, my mistake, you're right ! 
But I cannot explain why the bridge is not advertised when I specify the ip address of the host container, and advertised when the ip address of the docker container is specified.
From within the container, the host is reachable (pin).

**Comment by yfre** [comment]
@gpr7700  can we close this or is anything needs to be fixed in java hap code?

**Comment by gpr7700** [comment]
@yfre can be closed. As a workaround I configured docker with network mode : host.
