### ISSUE TITLE
Linked Services

### ISSUE THREAD

**Issue by scothi** [hap-java/HAP-Java#104]
Are there any plans to implement the Linked Services logic? 
I'm implementing - or at least trying to - the Television service which comes with two linked services (InputSource and TelevisionSpeaker) but I am having difficulties. I tried to add this functionality but it's not clear for me what is linked to what. Is the "sub" service linked to the "main" service or the linked attribute contains the sub service's ids?

**Comment by yfre** [comment]
i have implemented it for my irrigation system which has to be linked to valve services. but it was more hack than proper implementation.
in terms what is linked to what i would say, main services has an array with linked services IDs.

**Comment by scothi** [comment]
Ok, thanks. Now it’s working. :)

**Comment by yfre** [comment]
cool. will you push your changes to your repository or create PR here? i would love to integrate your changes to my branch.

**Comment by scothi** [comment]
PR #105

**Comment by dfrommi** [comment]
@scothi So you have a working Television service?
Would you mind sharing it, esp. the missing characteristics? I tried the same but I just can't get it working. 
No exceptions or errors, but the accessory is still shown as "not available" in the home app. 
I suspect that something is wrong with the characteristics, but I just can't find it.

**Comment by gjvanderheiden** [comment]
Could 

public void addLinkedService(Service service)

 be added to the interface Service.

I don't see how I can add a linked service when using hap-java.

**Comment by gjvanderheiden** [comment]
I would like to do this:

HomekitAccessory accessory = new MockSwitch(...);
accessory.addLinkedAccessory(new MockBatteryAccessory());

**Comment by yfre** [comment]
yes, it was  addLinkedAccessory was originally there in interface but then i have removed it to be consistent with Characterstics which has addCharacteristics only at AbstractServiceImpl but not in the interface. 

as of now you can do this
accessory.getServices().add(new Service())

but maybe we should really introduce addLinkedService at Service interface. maybe also the addCharacteristic as well. it is more developer friendly imo.

**Comment by yfre** [comment]
@gjvanderheiden  you are completely right, without adding addLinkedService to Service interface we cannot use it.  it was working only with test mock client as i could overwrite getService there. 
and it is also correct to add addCharacteristics to Service interface. characteristics are fixed and the developer should not add them manually one-by-one. 
let me prepare a PR with changes

**Comment by dfrommi** [comment]
I actually thought it could used like this:
- Some service is implementing `AbstractServiceImpl`, let's say `TelevisionService`
- The `TelevisionService` would expose a method like `addInputSource(InputSourceService s)`
  - this would be implemented as `super.addLinkedService(s)`

Do you see a problem with this approach? 

You can't link arbitrary services, so type-safety imho would make sense.

**Comment by yfre** [comment]
this is the approach @gjvanderheiden  was also proposing  - dedicated methods. 

my idea was to keep it more flexible as services can be combined in many different ways and HAP does not restrict it. e.g. you can add battery service to lightbulb or switch and home app shows it correctly. 
other examples are fan, slat and sensors which can be added to many other services like AirPurifier, Heating and other. 
so, we would need to add many methods for almost all combinations.

**Comment by dfrommi** [comment]
Ah, I see.
Didn't know that you can combine arbitrary services. Thanks.
