### ISSUE TITLE
IrrigationSystemAccessory doesnt have action 

### ISSUE THREAD

**Issue by palioza** [hap-java/HAP-Java#114]
Hello,

i added few sprinklers which implements IrrigationSystemAccessory.
I can see all of them it in Home application on iphone but pressing that "device" only shows configuration for that. No Action is made.

branch: master
JDK 8

**Comment by yfre** [comment]
IrrigationSystemAccessory requires valve services linked to it. irrigation is basically grouping several valves. the actual functionality is provided by vales.

however, linked services are not supported yet. Once this https://github.com/hap-java/HAP-Java/pull/110 is merged, you can add valves to irrigation. 

until then you can use valve directly.

**Comment by ccutrer** [comment]
#110 was merged quite some time ago, and I've tested an irrigation system with linked valves. Closing this now.
