### ISSUE TITLE
project still alive? new maintainers needed?

### ISSUE THREAD

**Issue by yfre** [hap-java/HAP-Java#153]
hey @andylintner  @timcharper @ccutrer  @gdombiak  @gjvanderheiden @MariusVolkhart @jvaclavovic @bjpbakker @j-mutter @Lemongrass3110 @catadincu @sobeos @martinhanes @oli-d @dfrommi 

it is pity to see good contributions  are getting lost / not merged
see https://github.com/hap-java/HAP-Java/issues/149
or https://github.com/hap-java/HAP-Java/pull/151
https://github.com/hap-java/HAP-Java/pull/116

any chance to reactivate this project? would additional maintainers help?

**Comment by ccutrer** [comment]
I kinda figured _you_ were the primary maintainer now @yfre ;). Java is not my primary (or secondary or even tertiary) language, so while I can occasionally send up a PR when I find something I want fixed, it definitely needs a review, and I don't feel qualified to review others' Java code.

**Comment by ccutrer** [comment]
> im happy contributor but i have no rights to review and merge PRs..

well, let's fix that then :)

**Comment by yfre** [comment]
> > im happy contributor but i have no rights to review and merge PRs..
> 
> well, let's fix that then :)

oh. it is that easy. thank you @ccutrer!
