### ISSUE TITLE
Add support for battery status indicator in accessories (in percentage)

### ISSUE THREAD

**Issue by JacekKac** [hap-java/HAP-Java#164]
It will be good to show full battery status in % not only a warning using LowBattery switch.

**Comment by yfre** [comment]
this is already support with "Battery Service"
here is the characteristic for %
https://github.com/hap-java/HAP-Java/blob/master/src/main/java/io/github/hapjava/characteristics/impl/battery/BatteryLevelCharacteristic.java

**Comment by JacekKac** [comment]
hm... can you tell me how to use in in openhab homekit binding?did't now where to submit this issue :(

**Comment by yfre** [comment]
you can submit this kind request directly at openhab addon
https://github.com/openhab/openhab-addons

but support for battery service is already implemented and will be available in the next openhab release 3.3, in around 2-3 weeks

**Comment by yfre** [comment]
check the documentation for latest snapshot 
https://next.openhab.org/addons/integrations/homekit/
the battery service is already there

**Comment by JacekKac** [comment]
ok! but i thought it will be implemented at the accessorie level : TemperatureSensor.BatteryLevel and home app will show it in accessory details or maybe you ment xxx .BatteryLowStatus which i already implemented. The case is i have battery powered temperature sensors, with TemperatureSensor.BatteryLow which is working fine, but i want to have detailed information about % of battery in TemperatureSensor details. (i saw on screens from homeapp that this is possible

**Comment by JacekKac** [comment]
oh! should i use multiple tags on one accessory to achieve this ?
