### ISSUE TITLE
HAP R17 and Homekit Certification Assistant 5.0

### ISSUE THREAD

**Issue by zcduthieEDS** [hap-java/HAP-Java#184]
Hi there,

Over the next few weeks I'll be working on a fork of this library to integrate a GarageDoorOpener Accessory (via a Bridge).
Running an instance of the latest code (version [2.0.6](https://github.com/hap-java/HAP-Java/commit/975485f2be3db04dac4302a374719802daa712e4)) against Homekit Certification Assistant 5 results in a few _HAP R17_ conformance errors - including (among others):

- HomekitBridge must have a Protocol Information Service
- GarageDoorOpener characteristic format types should be uint8 (currently int)
- Missing support for error responses via HTTP 207 MultiStatusResponse

Are there any plans for these in the next development iteration (`2.0.7`?). And if not, would you like me to create Pull Requests for fixes that I implement locally?

**Comment by ccutrer** [comment]
There are not currently any plans to implement any of those features, and PRs would be welcome.

I do have some questions for you though that possibly shouldn't be discussed publicly. Please email me at cody@cutrer.us.
