### ISSUE TITLE
ios 16.4 won't connect with fake bridge

### ISSUE THREAD

**Issue by kalwinskidawid** [hap-java/HAP-Java#186]
Hi, 
I am trying to create a fake bridge with several devices. I used the example from the `sample` branch. The service starts successfully, but when I try to connect through the QR code after waiting a while I get the message "Not found accessory". 
Is it works with ios 16.4?

**Comment by ccutrer** [comment]
Yes, I've been running it with all of the 16.4 betas and the final release. I've had no issues.

**Comment by kalwinskidawid** [comment]
I understand that you already have a production version prepared by yourself?  Can someone confirm if `sampe` is working properly?

**Comment by kalwinskidawid** [comment]
However I have one more question. Is it possible to put this fake bridge outside . So that I can control devices from outside the local network?

**Comment by ccutrer** [comment]
You need a "Home Hub" - either a HomePod or a newer gen Apple TV - signed in to your same iCloud account. It will show up in your home's settings in the Home app on your phone/iPad/Mac, and then your devices will automatically and transparently be available outside your network. No amount of port forwarding or putting the bridge directly on the public internet will make it externally accessible.
