### ISSUE TITLE
WindowCovering doesn't work

### ISSUE THREAD

**Issue by jrburk** [hap-java/HAP-Java#40]
When I use WindowCovering I get an error from the iOS Home app "Home couldn't connect to this accessory.". I don't see any error in the debug console.

**Comment by timcharper** [comment]
Duplicate of #56

**Comment by timcharper** [comment]
@beowulfe let's close this as a duplicate of #56; I can definitely reproduce this bug and it is caused by the inclusion of `HoldPositionCharacteristic`

**Comment by sobeos** [comment]
No update since 10 month. Why is the issue not closed?
