### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by jrburk** [hap-java/HAP-Java#41]
I want to enable HAP for an existing smart home gateway. The gateway has access control with different permissions configurable for individual users.

Using this library I don't I don't have the information who performed and action:

public CompletableFuture<Void> setSwitchState(boolean powerState) throws Exception

Can the current user (or even a session) be passed to that call. As an alternative it could been made available using a java.lang.ThreadLocal (which is a temporay hack until we have a proper solution).

**Comment by beowulfe** [comment]
There’s no concept of a “User” in HomeKit, so there’s nothing to pass.

**Comment by jrburk** [comment]
But the API has com.beowulfe.hap.HomekitAuthInfo to do the pairing. I assume the communication is encrypted using the keys stored by this interface.

It would be helpful to have that IOS user been passed or made available to the methods mentioned above.

**Comment by beowulfe** [comment]
There’s no ID for the user beyond the key. And only a single pairing can exist for a given HomeKit device, so there’s no multiuser.

**Comment by alexmuntean** [comment]
thanks @beowulfe . I didn't know there's no multipairing.. I was looking for that... I got it working with other users too (sharing in home app)

**Comment by yfre** [comment]
closing as users management is not supported by homekit
