### ISSUE TITLE
Not working on RaspberryPi or NanoPi

### ISSUE THREAD

**Issue by mkattner** [hap-java/HAP-Java#46]
Hey,

I'm trying to run your software samples on a raspberry pi or a nano pi.

The sample is forking fine on my Mac. When I start the sample on a raspberry pi, the bridge starts and I can see it on my iPhone. But I can't connect to it.

Same happens on a NanoPi.

What can be wrong?

Best,
Martin

**Comment by mvmn** [comment]
Can it be your wifi? Do you use wired or wireless connection to the Pi?

**Comment by timcharper** [comment]
@mkattner I bet you're binding to 127.0.0.1, instead of the IP of the raspberry PI.
