### ISSUE TITLE
WindowCovering not working

### ISSUE THREAD

**Issue by yfre** [hap-java/HAP-Java#56]
WindowCovering was not working for me. I get the message "Could not add home" in the home app. commenting out following lines in WindowCoveringService solved the issue
/**
		addCharacteristic(new HoldPositionCharacteristic(windowCovering));

		addCharacteristic(new ObstructionDetectedCharacteristic(() -> windowCovering.getObstructionDetected(),
				c -> windowCovering.subscribeObstructionDetected(c),
				() -> windowCovering.unsubscribeObstructionDetected()));

		if (windowCovering instanceof HorizontalTiltingWindowCovering) {
			addCharacteristic(new CurrentHorizontalTiltAngleCharacteristic(
					(HorizontalTiltingWindowCovering) windowCovering));
			addCharacteristic(new TargetHorizontalTiltAngleCharacteristic(
					(HorizontalTiltingWindowCovering) windowCovering));
		}
		if (windowCovering instanceof VerticalTiltingWindowCovering) {
			addCharacteristic(new CurrentVerticalTiltAngleCharacteristic(
					(VerticalTiltingWindowCovering) windowCovering));
			addCharacteristic(new TargetVerticalTiltAngleCharacteristic(
					(VerticalTiltingWindowCovering) windowCovering));
		}
 */

still unsure what is wrong with that characteristics.

**Comment by yfre** [comment]
here the json part generated for accessories that make home app to stop to work

```
{
"aid": 785117798,
"services": [
{
"iid": 1,
"type": "0000003E-0000-1000-8000-0026BB765291",
"characteristics": [
{
"iid": 2,
"type": "00000023-0000-1000-8000-0026BB765291",
"perms": [
"pr"
],
"format": "string",
"events": false,
"bonjour": false,
"description": "Name of the accessory",
"value": "Arbeitszimmer Rollladen",
"maxLen": 255
},
{
"iid": 3,
"type": "00000020-0000-1000-8000-0026BB765291",
"perms": [
"pr"
],
"format": "string",
"events": false,
"bonjour": false,
"description": "The name of the manufacturer",
"value": "none",
"maxLen": 255
},
{
"iid": 4,
"type": "00000021-0000-1000-8000-0026BB765291",
"perms": [
"pr"
],
"format": "string",
"events": false,
"bonjour": false,
"description": "The name of the model",
"value": "none",
"maxLen": 255
},
{
"iid": 5,
"type": "00000030-0000-1000-8000-0026BB765291",
"perms": [
"pr"
],
"format": "string",
"events": false,
"bonjour": false,
"description": "The serial number of the accessory",
"value": "none",
"maxLen": 255
},
{
"iid": 6,
"type": "00000014-0000-1000-8000-0026BB765291",
"perms": [
"pw"
],
"format": "bool",
"events": false,
"bonjour": false,
"description": "Identifies the accessory via a physical action on the accessory"
}
]
},
{
"iid": 7,
"type": "0000008C-0000-1000-8000-0026BB765291",
"characteristics": [
{
"iid": 8,
"type": "00000023-0000-1000-8000-0026BB765291",
"perms": [
"pr"
],
"format": "string",
"events": false,
"bonjour": false,
"description": "Name of the accessory",
"value": "Arbeitszimmer Rollladen",
"maxLen": 255
},
{
"iid": 9,
"type": "0000006D-0000-1000-8000-0026BB765291",
"perms": [
"pr",
"ev"
],
"format": "int",
"events": false,
"bonjour": false,
"description": "The current position",
"value": 100,
"minValue": 0,
"maxValue": 100,
"minStep": 1,
"unit": "%"
},
{
"iid": 10,
"type": "0000006F-0000-1000-8000-0026BB765291",
"perms": [
"pw"
],
"format": "bool",
"events": false,
"bonjour": false,
"description": "Whether or not to hold position",
"value": null
},
{
"iid": 11,
"type": "00000072-0000-1000-8000-0026BB765291",
"perms": [
"pr",
"ev"
],
"format": "int",
"events": false,
"bonjour": false,
"description": "The position state",
"value": 2,
"minValue": 0,
"maxValue": 2,
"minStep": 1
},
{
"iid": 12,
"type": "0000007C-0000-1000-8000-0026BB765291",
"perms": [
"pw",
"pr",
"ev"
],
"format": "int",
"events": false,
"bonjour": false,
"description": "The target position",
"value": 100,
"minValue": 0,
"maxValue": 100,
"minStep": 1,
"unit": "%"
},
{
"iid": 13,
"type": "00000024-0000-1000-8000-0026BB765291",
"perms": [
"pr",
"ev"
],
"format": "bool",
"events": false,
"bonjour": false,
"description": "An obstruction has been detected",
"value": false
}
]
}
]
}
```

**Comment by zbot473** [comment]
Same here

**Comment by timcharper** [comment]
Seems like one of the characteristics is misconfigured; I've stripped it back to the required characteristics, and it works;

https://github.com/timcharper/HAP-Java/commit/97de9aa5a3400e8e04ff012a915fda92be78d196

**Comment by jrburk** [comment]
> Seems like one of the characteristics is misconfigured; I've stripped it back to the required characteristics, and it works;
> 
> [timcharper@97de9aa](https://github.com/timcharper/HAP-Java/commit/97de9aa5a3400e8e04ff012a915fda92be78d196)

Hmm, can you post your code here. I think I have the minimal code, but the problem still exists.

**Comment by yfre** [comment]
> > Seems like one of the characteristics is misconfigured; I've stripped it back to the required characteristics, and it works;
> > [timcharper@97de9aa](https://github.com/timcharper/HAP-Java/commit/97de9aa5a3400e8e04ff012a915fda92be78d196)
> 
> Hmm, can you post your code here. I think I have the minimal code, but the problem still exists.

in class WindowCoveringService i commented out following lines
`/**
addCharacteristic(new HoldPositionCharacteristic(windowCovering));
addCharacteristic(new ObstructionDetectedCharacteristic(() -> windowCovering.getObstructionDetected(),
			c -> windowCovering.subscribeObstructionDetected(c),
			() -> windowCovering.unsubscribeObstructionDetected()));

if (windowCovering instanceof HorizontalTiltingWindowCovering) {
		addCharacteristic(new CurrentHorizontalTiltAngleCharacteristic((HorizontalTiltingWindowCovering) windowCovering));
		addCharacteristic(new TargetHorizontalTiltAngleCharacteristic((HorizontalTiltingWindowCovering) windowCovering));
	}
if (windowCovering instanceof VerticalTiltingWindowCovering) {
	addCharacteristic(new CurrentVerticalTiltAngleCharacteristic((VerticalTiltingWindowCovering) windowCovering));
	addCharacteristic(new TargetVerticalTiltAngleCharacteristic((VerticalTiltingWindowCovering) windowCovering));
	}
*/`

**Comment by jrburk** [comment]
Thank you. Now it's working for me too...

**Comment by timcharper** [comment]
I've narrowed it down to `HoldPositionCharacteristic`, FYI

**Comment by timcharper** [comment]
@jrburk I still have no idea why HoldPositionCharacteristic is causing this. The latest release will use BasicWindowCovering, in the meantime.

**Comment by sobeos** [comment]
Any news on window coverings? I have horizontal tilting window coverings. HorizontalTiltingWindowCovering extends WindowCovering. WindowCovering is deprecated.

**Comment by sobeos** [comment]
> I still have no idea why HoldPositionCharacteristic is causing this.

Problem is that the characteristic is write only.
Homekit complains:
"Non-readable characteristics must not contain 'value' key".
The problem is in BaseCharacteristic -> makeBuilder

**Comment by sobeos** [comment]
Looks like 
              if (isReadable) {
                setJsonValue(builder, value);
              }
is fixing the problem.

**Comment by timcharper** [comment]
Great find! Would you mind opening up a pull request?
