### ISSUE TITLE
Migrate project to organization

### ISSUE THREAD

**Issue by timcharper** [hap-java/HAP-Java#71]
@beowulfe wdyt if we migrate this repository to an organization so others can help with the review process and unblock merges?

I created an org and invited you to it:

https://github.com/hap-java

**Comment by timcharper** [comment]
@beowulfe I know your busy... can you respond here? We're both feeling a little blocked and I'm feeling more and more anxious about being so far away from master

**Comment by timcharper** [comment]
Hey @beowulfe! It seems you're pretty overwhelmed at the moment. @ccutrer and I are going to proceed to fork this repo to the organization we created and migrate any outstanding PRs over there. We've been doing work on the fork of Homekit there, also.

**Comment by beowulfe** [comment]
@timcharper - I'm good with that. Let's make that the official home. I definitely don't have the bandwidth to maintain this.

**Comment by beowulfe** [comment]
Oh, would you rather I transfer this one instead of fork?

**Comment by timcharper** [comment]
Oh, hey @beowulfe !  I think it would be better to migrate it. You have an invite to join the org, did you see it?

**Comment by beowulfe** [comment]
Done. Thanks for setting this up. Happy to see it!
