### ISSUE TITLE
Future releases

### ISSUE THREAD

**Issue by andylintner** [hap-java/HAP-Java#73]
What do you guys want to do about release publication? This was previously published to Sonatype's OSS repo, but under my personal coordinates (com.beowulfe)

I suggest you come up with a new package name and publish under that. Let me know if you want any help.

**Comment by timcharper** [comment]
👋 Let's get a final 1.1.x release out under `com.beowulfe`, and then future releases can be done under `io.github.hap-java`

**Comment by timcharper** [comment]
https://issues.sonatype.org/browse/OSSRH-46876

**Comment by timcharper** [comment]
@beowulfe I've tagged and pushed 1.1.5; could you publish it? https://github.com/hap-java/HAP-Java/releases/tag/hap-1.1.5

**Comment by J-N-K** [comment]
Isn't `com.github.hap-java` more common?

**Comment by yfre** [comment]
solved, new release was published
