### ISSUE TITLE
Unnecessary EVENT message / performance issue

### ISSUE THREAD

**Issue by yfre** [hap-java/HAP-Java#83]
According to HAP spec. the controller should confirm subscription to an event with a 204 No Content HTTP status code and an empty body.

An EVENT message should be only send on value changes.

Currently we send EVENT message on subscription, i.e. current sequence:
Receive: /characteristics
Send: 204 No Content
Send: EVENT

the last one is not required and leads to performance issues

**Comment by ccutrer** [comment]
Do you think this is related or exacerbated in iOS 13? My OpenHAB/HomeKit has gone to craps in iOS 13, causing constant reconnection issues.

**Comment by yfre** [comment]
exactly. in ios12 it was an unnecessary message but it was working. 
but with ios13 it become unusable, home app was keeping refreshing and reconnecting all the time.
